https://www.kaggle.com/c/digit-recognizer

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import keras

Using TensorFlow backend.


# Import Data

In [2]:
train_images = pd.read_csv('train.csv')

In [3]:
test_images = pd.read_csv('test.csv')

# EDA

In [4]:
train_images.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [5]:
test_images.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

# Train Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_images.drop(['label'], axis=1), train_images['label'])

In [7]:
from sklearn.metrics import confusion_matrix, classification_report

# Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[1011    1    5    3    3   10    8    2    2    5]
 [   0 1086   11    3    2    2    5    3   20    1]
 [  13   21  872   24   15   12   17   25   31    6]
 [   5   10   27  985    2   42    4   12   18   19]
 [   3    7   11    2  915    3    5    3    8   44]
 [   6   14   16   46   14  828   20    5   28    9]
 [   7    9    8    0    7   15  972    1    6    1]
 [   4    9   11    5    8    5    0 1001    5   37]
 [   9   27    8   32   14   18   11    6  892   16]
 [   8    6    8   21   27   12    0   45    4  895]]
             precision    recall  f1-score   support

          0       0.95      0.96      0.96      1050
          1       0.91      0.96      0.93      1133
          2       0.89      0.84      0.87      1036
          3       0.88      0.88      0.88      1124
          4       0.91      0.91      0.91      1001
          5       0.87      0.84      0.86       986
          6       0.93      0.95      0.94      1026
          7       0.91      0.92      0.91  

In [9]:
model = LogisticRegression()
model.fit(train_images.drop(['label'], axis=1), train_images['label'])
pred =  model.predict(test_images)

predictions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(pred, columns=['Label'])], axis=1)
predictions.to_csv('LogisticRegression.csv', index=False)

# Random Forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10)
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[1031    0    3    1    1    0   10    0    3    1]
 [   0 1112    9    3    3    1    0    1    3    1]
 [  16    4  952   16    9    2    4   16   14    3]
 [   8    6   20 1018    0   33    2   15   15    7]
 [   2    3    4    0  947    2    8    2    3   30]
 [  11    3    3   37    7  895    6    2   14    8]
 [   9    4    6    0    3   13  986    0    5    0]
 [   1    8   20    1   11    2    0 1028    4   10]
 [   5   10   13   31    4   15   12    2  928   13]
 [  13    3    9   16   33    9    3   14    9  917]]
             precision    recall  f1-score   support

          0       0.94      0.98      0.96      1050
          1       0.96      0.98      0.97      1133
          2       0.92      0.92      0.92      1036
          3       0.91      0.91      0.91      1124
          4       0.93      0.95      0.94      1001
          5       0.92      0.91      0.91       986
          6       0.96      0.96      0.96      1026
          7       0.95      0.95      0.95  

In [11]:
model = RandomForestClassifier(n_estimators=10)
model.fit(train_images.drop(['label'], axis=1), train_images['label'])
pred =  model.predict(test_images)

predictions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(pred, columns=['Label'])], axis=1)
predictions.to_csv('RandomForest.csv', index=False)

# Gaussian Naive Bayes

In [12]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 937    1    4    6    3    2   47    1   36   13]
 [   0 1072    2    3    1    4   14    0   26   11]
 [ 107   27  258   81    5    4  317    4  210   23]
 [  90   68    8  329    2    2   82    8  413  122]
 [  31    6    9    3  128    5  100    5  247  467]
 [ 130   28    6   18    7   53   59    1  584  100]
 [  12   15    5    0    1    1  972    0   18    2]
 [   4   11    1   10    6    1    4  343   37  668]
 [  15  140    4   12    3    5   25    2  624  203]
 [  12    8    7    0    5    1    0    9   26  958]]
             precision    recall  f1-score   support

          0       0.70      0.89      0.78      1050
          1       0.78      0.95      0.85      1133
          2       0.85      0.25      0.39      1036
          3       0.71      0.29      0.41      1124
          4       0.80      0.13      0.22      1001
          5       0.68      0.05      0.10       986
          6       0.60      0.95      0.73      1026
          7       0.92      0.32      0.47  

In [13]:
model = GaussianNB()
model.fit(train_images.drop(['label'], axis=1), train_images['label'])
pred =  model.predict(test_images)

predictions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(pred, columns=['Label'])], axis=1)
predictions.to_csv('GaussianNB.csv', index=False)

# Multinomial Naive Bayes

In [14]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 957    0    6    4    2    7   17    0   56    1]
 [   0 1062    8    2    0    7    8    1   43    2]
 [  16   12  839   22   18    3   49   16   55    6]
 [   5   15   55  907    2   20   16   11   54   39]
 [   2    3    7    0  739    2   15    2   45  186]
 [  24    8   12  116   21  646   24    3   90   42]
 [  12   18    5    0    6   26  948    0   11    0]
 [   5   17   11    7   19    1    0  911   25   89]
 [   6   56    8   62   10   39   11    2  797   42]
 [  13    9    5   14   74    7    0   30   32  842]]
             precision    recall  f1-score   support

          0       0.92      0.91      0.92      1050
          1       0.89      0.94      0.91      1133
          2       0.88      0.81      0.84      1036
          3       0.80      0.81      0.80      1124
          4       0.83      0.74      0.78      1001
          5       0.85      0.66      0.74       986
          6       0.87      0.92      0.90      1026
          7       0.93      0.84      0.88  

In [15]:
model = MultinomialNB()
model.fit(train_images.drop(['label'], axis=1), train_images['label'])
pred =  model.predict(test_images)

predictions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(pred, columns=['Label'])], axis=1)
predictions.to_csv('MultinomialNB.csv', index=False)

# Bernoulli Naive Bayes

In [16]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 937    0    6    4    1   56   22    0   24    0]
 [   0 1088   13    0    1   12    6    0   11    2]
 [  20   14  831   27   27    6   45   18   41    7]
 [   7   23   51  897    2   21   11   19   53   40]
 [   0   12    5    0  801    7   14    5   26  131]
 [  33   18   11  136   29  681   22    7   17   32]
 [  16   26   13    0    7   31  928    0    5    0]
 [   4   22   10    5   19    2    0  931   15   77]
 [  10   39   10   92    8   26   11    0  785   52]
 [  18   17    5   16   80    6    0   42   22  820]]
             precision    recall  f1-score   support

          0       0.90      0.89      0.89      1050
          1       0.86      0.96      0.91      1133
          2       0.87      0.80      0.83      1036
          3       0.76      0.80      0.78      1124
          4       0.82      0.80      0.81      1001
          5       0.80      0.69      0.74       986
          6       0.88      0.90      0.89      1026
          7       0.91      0.86      0.88  

In [17]:
model = BernoulliNB()
model.fit(train_images.drop(['label'], axis=1), train_images['label'])
pred =  model.predict(test_images)

predictions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(pred, columns=['Label'])], axis=1)
predictions.to_csv('BernoulliNB.csv', index=False)

# Softmax Network

## Preprocessing

In [18]:
import math
def random_mini_batches(X, Y, mini_batch_size = 128, seed = 0):

    m = X.shape[0]                  # number of training examples
    mini_batches = []
    np.random.seed(seed)
    
    # Step 1: Shuffle (X, Y)
    permutation = list(np.random.permutation(m))
    shuffled_X = X[permutation,:]
    shuffled_Y = Y[permutation,:]

    # Step 2: Partition (shuffled_X, shuffled_Y). Minus the end case.
    num_complete_minibatches = math.floor(m/mini_batch_size) 
    # number of mini batches of size mini_batch_size in your partitionning
    for k in range(0, num_complete_minibatches):
        mini_batch_X = shuffled_X[k * mini_batch_size : k * mini_batch_size + mini_batch_size,:]
        mini_batch_Y = shuffled_Y[k * mini_batch_size : k * mini_batch_size + mini_batch_size,:]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)
    
    # Handling the end case (last mini-batch < mini_batch_size)
    if m % mini_batch_size != 0:
        mini_batch_X = shuffled_X[num_complete_minibatches * mini_batch_size : m,:]
        mini_batch_Y = shuffled_Y[num_complete_minibatches * mini_batch_size : m,:]
        mini_batch = (mini_batch_X, mini_batch_Y)
        mini_batches.append(mini_batch)
    
    return mini_batches

In [19]:
X_trainN = X_train.as_matrix()
X_testN = X_test.as_matrix()
y_trainN = y_train.values
y_testN = y_test.values

D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [20]:
from sklearn.preprocessing import OneHotEncoder
enc1 = OneHotEncoder(sparse=False)
y_trainN = enc1.fit_transform(y_trainN.reshape(-1,1),)

enc2 = OneHotEncoder(sparse=False)
y_testN = enc2.fit_transform(y_testN.reshape(-1,1),)


In [21]:
# placeholder
x = tf.placeholder(tf.float32, shape=[None, 784])

In [22]:
# variables
w = tf.Variable(tf.random_normal([784,10], mean=0.0, stddev=0.1))
b = tf.Variable(tf.random_normal([10]))

In [23]:
# operation
y = tf.add(tf.matmul(x, w), b)

In [24]:
# loss function
y_true = tf.placeholder(tf.float32, [None, 10])
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [25]:
# optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)
train = optimizer.minimize(cross_entropy)

In [26]:
# create session
init = tf.global_variables_initializer()

In [27]:
# run session
with tf.Session() as sess:
    sess.run(init)
    minibatches = random_mini_batches(X_trainN,y_trainN)
    for epochs in range(150):
        for minibatch in minibatches:
            (mini_x,mini_y) = minibatch
            sess.run(train, feed_dict={x:mini_x, y_true:mini_y})
    
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_true, 1))
    acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print(sess.run(acc, feed_dict={x:X_testN, y_true:y_testN}))
    print(sess.run(y, feed_dict={x:test_images.as_matrix()}))

0.864762
[[ 128527.203125   -486943.625       466197.4375     ...,  -59581.0703125
    30932.734375    -68819.5703125 ]
 [ 410934.40625    -101613.0390625    93522.96875    ..., -125434.7890625
    -8328.10351562 -207485.40625   ]
 [-104054.2890625   -30934.86328125    4238.52587891 ...,   -4033.52978516
    39352.05859375  110207.3515625 ]
 ..., 
 [ -99344.859375    -29683.734375     21272.72070312 ...,   35837.125
    22175.50390625   49242.48828125]
 [-130654.34375    -163476.0625      -94152.015625   ...,   32013.04492188
     3756.89819336  229820.734375  ]
 [  58164.18359375 -311250.15625     313595.0625     ..., -247520.609375
    74998.390625     -8352.02148438]]


D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  del sys.path[0]


# Estimators API

In [28]:
for i in range(784):
    print("pixel"+str(i)+" = tf.feature_column.numeric_column('pixel"+str(i)+"')")

pixel0 = tf.feature_column.numeric_column('pixel0')
pixel1 = tf.feature_column.numeric_column('pixel1')
pixel2 = tf.feature_column.numeric_column('pixel2')
pixel3 = tf.feature_column.numeric_column('pixel3')
pixel4 = tf.feature_column.numeric_column('pixel4')
pixel5 = tf.feature_column.numeric_column('pixel5')
pixel6 = tf.feature_column.numeric_column('pixel6')
pixel7 = tf.feature_column.numeric_column('pixel7')
pixel8 = tf.feature_column.numeric_column('pixel8')
pixel9 = tf.feature_column.numeric_column('pixel9')
pixel10 = tf.feature_column.numeric_column('pixel10')
pixel11 = tf.feature_column.numeric_column('pixel11')
pixel12 = tf.feature_column.numeric_column('pixel12')
pixel13 = tf.feature_column.numeric_column('pixel13')
pixel14 = tf.feature_column.numeric_column('pixel14')
pixel15 = tf.feature_column.numeric_column('pixel15')
pixel16 = tf.feature_column.numeric_column('pixel16')
pixel17 = tf.feature_column.numeric_column('pixel17')
pixel18 = tf.feature_column.numeric_column('pixe

In [29]:
pixel0 = tf.feature_column.numeric_column('pixel0')
pixel1 = tf.feature_column.numeric_column('pixel1')
pixel2 = tf.feature_column.numeric_column('pixel2')
pixel3 = tf.feature_column.numeric_column('pixel3')
pixel4 = tf.feature_column.numeric_column('pixel4')
pixel5 = tf.feature_column.numeric_column('pixel5')
pixel6 = tf.feature_column.numeric_column('pixel6')
pixel7 = tf.feature_column.numeric_column('pixel7')
pixel8 = tf.feature_column.numeric_column('pixel8')
pixel9 = tf.feature_column.numeric_column('pixel9')
pixel10 = tf.feature_column.numeric_column('pixel10')
pixel11 = tf.feature_column.numeric_column('pixel11')
pixel12 = tf.feature_column.numeric_column('pixel12')
pixel13 = tf.feature_column.numeric_column('pixel13')
pixel14 = tf.feature_column.numeric_column('pixel14')
pixel15 = tf.feature_column.numeric_column('pixel15')
pixel16 = tf.feature_column.numeric_column('pixel16')
pixel17 = tf.feature_column.numeric_column('pixel17')
pixel18 = tf.feature_column.numeric_column('pixel18')
pixel19 = tf.feature_column.numeric_column('pixel19')
pixel20 = tf.feature_column.numeric_column('pixel20')
pixel21 = tf.feature_column.numeric_column('pixel21')
pixel22 = tf.feature_column.numeric_column('pixel22')
pixel23 = tf.feature_column.numeric_column('pixel23')
pixel24 = tf.feature_column.numeric_column('pixel24')
pixel25 = tf.feature_column.numeric_column('pixel25')
pixel26 = tf.feature_column.numeric_column('pixel26')
pixel27 = tf.feature_column.numeric_column('pixel27')
pixel28 = tf.feature_column.numeric_column('pixel28')
pixel29 = tf.feature_column.numeric_column('pixel29')
pixel30 = tf.feature_column.numeric_column('pixel30')
pixel31 = tf.feature_column.numeric_column('pixel31')
pixel32 = tf.feature_column.numeric_column('pixel32')
pixel33 = tf.feature_column.numeric_column('pixel33')
pixel34 = tf.feature_column.numeric_column('pixel34')
pixel35 = tf.feature_column.numeric_column('pixel35')
pixel36 = tf.feature_column.numeric_column('pixel36')
pixel37 = tf.feature_column.numeric_column('pixel37')
pixel38 = tf.feature_column.numeric_column('pixel38')
pixel39 = tf.feature_column.numeric_column('pixel39')
pixel40 = tf.feature_column.numeric_column('pixel40')
pixel41 = tf.feature_column.numeric_column('pixel41')
pixel42 = tf.feature_column.numeric_column('pixel42')
pixel43 = tf.feature_column.numeric_column('pixel43')
pixel44 = tf.feature_column.numeric_column('pixel44')
pixel45 = tf.feature_column.numeric_column('pixel45')
pixel46 = tf.feature_column.numeric_column('pixel46')
pixel47 = tf.feature_column.numeric_column('pixel47')
pixel48 = tf.feature_column.numeric_column('pixel48')
pixel49 = tf.feature_column.numeric_column('pixel49')
pixel50 = tf.feature_column.numeric_column('pixel50')
pixel51 = tf.feature_column.numeric_column('pixel51')
pixel52 = tf.feature_column.numeric_column('pixel52')
pixel53 = tf.feature_column.numeric_column('pixel53')
pixel54 = tf.feature_column.numeric_column('pixel54')
pixel55 = tf.feature_column.numeric_column('pixel55')
pixel56 = tf.feature_column.numeric_column('pixel56')
pixel57 = tf.feature_column.numeric_column('pixel57')
pixel58 = tf.feature_column.numeric_column('pixel58')
pixel59 = tf.feature_column.numeric_column('pixel59')
pixel60 = tf.feature_column.numeric_column('pixel60')
pixel61 = tf.feature_column.numeric_column('pixel61')
pixel62 = tf.feature_column.numeric_column('pixel62')
pixel63 = tf.feature_column.numeric_column('pixel63')
pixel64 = tf.feature_column.numeric_column('pixel64')
pixel65 = tf.feature_column.numeric_column('pixel65')
pixel66 = tf.feature_column.numeric_column('pixel66')
pixel67 = tf.feature_column.numeric_column('pixel67')
pixel68 = tf.feature_column.numeric_column('pixel68')
pixel69 = tf.feature_column.numeric_column('pixel69')
pixel70 = tf.feature_column.numeric_column('pixel70')
pixel71 = tf.feature_column.numeric_column('pixel71')
pixel72 = tf.feature_column.numeric_column('pixel72')
pixel73 = tf.feature_column.numeric_column('pixel73')
pixel74 = tf.feature_column.numeric_column('pixel74')
pixel75 = tf.feature_column.numeric_column('pixel75')
pixel76 = tf.feature_column.numeric_column('pixel76')
pixel77 = tf.feature_column.numeric_column('pixel77')
pixel78 = tf.feature_column.numeric_column('pixel78')
pixel79 = tf.feature_column.numeric_column('pixel79')
pixel80 = tf.feature_column.numeric_column('pixel80')
pixel81 = tf.feature_column.numeric_column('pixel81')
pixel82 = tf.feature_column.numeric_column('pixel82')
pixel83 = tf.feature_column.numeric_column('pixel83')
pixel84 = tf.feature_column.numeric_column('pixel84')
pixel85 = tf.feature_column.numeric_column('pixel85')
pixel86 = tf.feature_column.numeric_column('pixel86')
pixel87 = tf.feature_column.numeric_column('pixel87')
pixel88 = tf.feature_column.numeric_column('pixel88')
pixel89 = tf.feature_column.numeric_column('pixel89')
pixel90 = tf.feature_column.numeric_column('pixel90')
pixel91 = tf.feature_column.numeric_column('pixel91')
pixel92 = tf.feature_column.numeric_column('pixel92')
pixel93 = tf.feature_column.numeric_column('pixel93')
pixel94 = tf.feature_column.numeric_column('pixel94')
pixel95 = tf.feature_column.numeric_column('pixel95')
pixel96 = tf.feature_column.numeric_column('pixel96')
pixel97 = tf.feature_column.numeric_column('pixel97')
pixel98 = tf.feature_column.numeric_column('pixel98')
pixel99 = tf.feature_column.numeric_column('pixel99')
pixel100 = tf.feature_column.numeric_column('pixel100')
pixel101 = tf.feature_column.numeric_column('pixel101')
pixel102 = tf.feature_column.numeric_column('pixel102')
pixel103 = tf.feature_column.numeric_column('pixel103')
pixel104 = tf.feature_column.numeric_column('pixel104')
pixel105 = tf.feature_column.numeric_column('pixel105')
pixel106 = tf.feature_column.numeric_column('pixel106')
pixel107 = tf.feature_column.numeric_column('pixel107')
pixel108 = tf.feature_column.numeric_column('pixel108')
pixel109 = tf.feature_column.numeric_column('pixel109')
pixel110 = tf.feature_column.numeric_column('pixel110')
pixel111 = tf.feature_column.numeric_column('pixel111')
pixel112 = tf.feature_column.numeric_column('pixel112')
pixel113 = tf.feature_column.numeric_column('pixel113')
pixel114 = tf.feature_column.numeric_column('pixel114')
pixel115 = tf.feature_column.numeric_column('pixel115')
pixel116 = tf.feature_column.numeric_column('pixel116')
pixel117 = tf.feature_column.numeric_column('pixel117')
pixel118 = tf.feature_column.numeric_column('pixel118')
pixel119 = tf.feature_column.numeric_column('pixel119')
pixel120 = tf.feature_column.numeric_column('pixel120')
pixel121 = tf.feature_column.numeric_column('pixel121')
pixel122 = tf.feature_column.numeric_column('pixel122')
pixel123 = tf.feature_column.numeric_column('pixel123')
pixel124 = tf.feature_column.numeric_column('pixel124')
pixel125 = tf.feature_column.numeric_column('pixel125')
pixel126 = tf.feature_column.numeric_column('pixel126')
pixel127 = tf.feature_column.numeric_column('pixel127')
pixel128 = tf.feature_column.numeric_column('pixel128')
pixel129 = tf.feature_column.numeric_column('pixel129')
pixel130 = tf.feature_column.numeric_column('pixel130')
pixel131 = tf.feature_column.numeric_column('pixel131')
pixel132 = tf.feature_column.numeric_column('pixel132')
pixel133 = tf.feature_column.numeric_column('pixel133')
pixel134 = tf.feature_column.numeric_column('pixel134')
pixel135 = tf.feature_column.numeric_column('pixel135')
pixel136 = tf.feature_column.numeric_column('pixel136')
pixel137 = tf.feature_column.numeric_column('pixel137')
pixel138 = tf.feature_column.numeric_column('pixel138')
pixel139 = tf.feature_column.numeric_column('pixel139')
pixel140 = tf.feature_column.numeric_column('pixel140')
pixel141 = tf.feature_column.numeric_column('pixel141')
pixel142 = tf.feature_column.numeric_column('pixel142')
pixel143 = tf.feature_column.numeric_column('pixel143')
pixel144 = tf.feature_column.numeric_column('pixel144')
pixel145 = tf.feature_column.numeric_column('pixel145')
pixel146 = tf.feature_column.numeric_column('pixel146')
pixel147 = tf.feature_column.numeric_column('pixel147')
pixel148 = tf.feature_column.numeric_column('pixel148')
pixel149 = tf.feature_column.numeric_column('pixel149')
pixel150 = tf.feature_column.numeric_column('pixel150')
pixel151 = tf.feature_column.numeric_column('pixel151')
pixel152 = tf.feature_column.numeric_column('pixel152')
pixel153 = tf.feature_column.numeric_column('pixel153')
pixel154 = tf.feature_column.numeric_column('pixel154')
pixel155 = tf.feature_column.numeric_column('pixel155')
pixel156 = tf.feature_column.numeric_column('pixel156')
pixel157 = tf.feature_column.numeric_column('pixel157')
pixel158 = tf.feature_column.numeric_column('pixel158')
pixel159 = tf.feature_column.numeric_column('pixel159')
pixel160 = tf.feature_column.numeric_column('pixel160')
pixel161 = tf.feature_column.numeric_column('pixel161')
pixel162 = tf.feature_column.numeric_column('pixel162')
pixel163 = tf.feature_column.numeric_column('pixel163')
pixel164 = tf.feature_column.numeric_column('pixel164')
pixel165 = tf.feature_column.numeric_column('pixel165')
pixel166 = tf.feature_column.numeric_column('pixel166')
pixel167 = tf.feature_column.numeric_column('pixel167')
pixel168 = tf.feature_column.numeric_column('pixel168')
pixel169 = tf.feature_column.numeric_column('pixel169')
pixel170 = tf.feature_column.numeric_column('pixel170')
pixel171 = tf.feature_column.numeric_column('pixel171')
pixel172 = tf.feature_column.numeric_column('pixel172')
pixel173 = tf.feature_column.numeric_column('pixel173')
pixel174 = tf.feature_column.numeric_column('pixel174')
pixel175 = tf.feature_column.numeric_column('pixel175')
pixel176 = tf.feature_column.numeric_column('pixel176')
pixel177 = tf.feature_column.numeric_column('pixel177')
pixel178 = tf.feature_column.numeric_column('pixel178')
pixel179 = tf.feature_column.numeric_column('pixel179')
pixel180 = tf.feature_column.numeric_column('pixel180')
pixel181 = tf.feature_column.numeric_column('pixel181')
pixel182 = tf.feature_column.numeric_column('pixel182')
pixel183 = tf.feature_column.numeric_column('pixel183')
pixel184 = tf.feature_column.numeric_column('pixel184')
pixel185 = tf.feature_column.numeric_column('pixel185')
pixel186 = tf.feature_column.numeric_column('pixel186')
pixel187 = tf.feature_column.numeric_column('pixel187')
pixel188 = tf.feature_column.numeric_column('pixel188')
pixel189 = tf.feature_column.numeric_column('pixel189')
pixel190 = tf.feature_column.numeric_column('pixel190')
pixel191 = tf.feature_column.numeric_column('pixel191')
pixel192 = tf.feature_column.numeric_column('pixel192')
pixel193 = tf.feature_column.numeric_column('pixel193')
pixel194 = tf.feature_column.numeric_column('pixel194')
pixel195 = tf.feature_column.numeric_column('pixel195')
pixel196 = tf.feature_column.numeric_column('pixel196')
pixel197 = tf.feature_column.numeric_column('pixel197')
pixel198 = tf.feature_column.numeric_column('pixel198')
pixel199 = tf.feature_column.numeric_column('pixel199')
pixel200 = tf.feature_column.numeric_column('pixel200')
pixel201 = tf.feature_column.numeric_column('pixel201')
pixel202 = tf.feature_column.numeric_column('pixel202')
pixel203 = tf.feature_column.numeric_column('pixel203')
pixel204 = tf.feature_column.numeric_column('pixel204')
pixel205 = tf.feature_column.numeric_column('pixel205')
pixel206 = tf.feature_column.numeric_column('pixel206')
pixel207 = tf.feature_column.numeric_column('pixel207')
pixel208 = tf.feature_column.numeric_column('pixel208')
pixel209 = tf.feature_column.numeric_column('pixel209')
pixel210 = tf.feature_column.numeric_column('pixel210')
pixel211 = tf.feature_column.numeric_column('pixel211')
pixel212 = tf.feature_column.numeric_column('pixel212')
pixel213 = tf.feature_column.numeric_column('pixel213')
pixel214 = tf.feature_column.numeric_column('pixel214')
pixel215 = tf.feature_column.numeric_column('pixel215')
pixel216 = tf.feature_column.numeric_column('pixel216')
pixel217 = tf.feature_column.numeric_column('pixel217')
pixel218 = tf.feature_column.numeric_column('pixel218')
pixel219 = tf.feature_column.numeric_column('pixel219')
pixel220 = tf.feature_column.numeric_column('pixel220')
pixel221 = tf.feature_column.numeric_column('pixel221')
pixel222 = tf.feature_column.numeric_column('pixel222')
pixel223 = tf.feature_column.numeric_column('pixel223')
pixel224 = tf.feature_column.numeric_column('pixel224')
pixel225 = tf.feature_column.numeric_column('pixel225')
pixel226 = tf.feature_column.numeric_column('pixel226')
pixel227 = tf.feature_column.numeric_column('pixel227')
pixel228 = tf.feature_column.numeric_column('pixel228')
pixel229 = tf.feature_column.numeric_column('pixel229')
pixel230 = tf.feature_column.numeric_column('pixel230')
pixel231 = tf.feature_column.numeric_column('pixel231')
pixel232 = tf.feature_column.numeric_column('pixel232')
pixel233 = tf.feature_column.numeric_column('pixel233')
pixel234 = tf.feature_column.numeric_column('pixel234')
pixel235 = tf.feature_column.numeric_column('pixel235')
pixel236 = tf.feature_column.numeric_column('pixel236')
pixel237 = tf.feature_column.numeric_column('pixel237')
pixel238 = tf.feature_column.numeric_column('pixel238')
pixel239 = tf.feature_column.numeric_column('pixel239')
pixel240 = tf.feature_column.numeric_column('pixel240')
pixel241 = tf.feature_column.numeric_column('pixel241')
pixel242 = tf.feature_column.numeric_column('pixel242')
pixel243 = tf.feature_column.numeric_column('pixel243')
pixel244 = tf.feature_column.numeric_column('pixel244')
pixel245 = tf.feature_column.numeric_column('pixel245')
pixel246 = tf.feature_column.numeric_column('pixel246')
pixel247 = tf.feature_column.numeric_column('pixel247')
pixel248 = tf.feature_column.numeric_column('pixel248')
pixel249 = tf.feature_column.numeric_column('pixel249')
pixel250 = tf.feature_column.numeric_column('pixel250')
pixel251 = tf.feature_column.numeric_column('pixel251')
pixel252 = tf.feature_column.numeric_column('pixel252')
pixel253 = tf.feature_column.numeric_column('pixel253')
pixel254 = tf.feature_column.numeric_column('pixel254')
pixel255 = tf.feature_column.numeric_column('pixel255')
pixel256 = tf.feature_column.numeric_column('pixel256')
pixel257 = tf.feature_column.numeric_column('pixel257')
pixel258 = tf.feature_column.numeric_column('pixel258')
pixel259 = tf.feature_column.numeric_column('pixel259')
pixel260 = tf.feature_column.numeric_column('pixel260')
pixel261 = tf.feature_column.numeric_column('pixel261')
pixel262 = tf.feature_column.numeric_column('pixel262')
pixel263 = tf.feature_column.numeric_column('pixel263')
pixel264 = tf.feature_column.numeric_column('pixel264')
pixel265 = tf.feature_column.numeric_column('pixel265')
pixel266 = tf.feature_column.numeric_column('pixel266')
pixel267 = tf.feature_column.numeric_column('pixel267')
pixel268 = tf.feature_column.numeric_column('pixel268')
pixel269 = tf.feature_column.numeric_column('pixel269')
pixel270 = tf.feature_column.numeric_column('pixel270')
pixel271 = tf.feature_column.numeric_column('pixel271')
pixel272 = tf.feature_column.numeric_column('pixel272')
pixel273 = tf.feature_column.numeric_column('pixel273')
pixel274 = tf.feature_column.numeric_column('pixel274')
pixel275 = tf.feature_column.numeric_column('pixel275')
pixel276 = tf.feature_column.numeric_column('pixel276')
pixel277 = tf.feature_column.numeric_column('pixel277')
pixel278 = tf.feature_column.numeric_column('pixel278')
pixel279 = tf.feature_column.numeric_column('pixel279')
pixel280 = tf.feature_column.numeric_column('pixel280')
pixel281 = tf.feature_column.numeric_column('pixel281')
pixel282 = tf.feature_column.numeric_column('pixel282')
pixel283 = tf.feature_column.numeric_column('pixel283')
pixel284 = tf.feature_column.numeric_column('pixel284')
pixel285 = tf.feature_column.numeric_column('pixel285')
pixel286 = tf.feature_column.numeric_column('pixel286')
pixel287 = tf.feature_column.numeric_column('pixel287')
pixel288 = tf.feature_column.numeric_column('pixel288')
pixel289 = tf.feature_column.numeric_column('pixel289')
pixel290 = tf.feature_column.numeric_column('pixel290')
pixel291 = tf.feature_column.numeric_column('pixel291')
pixel292 = tf.feature_column.numeric_column('pixel292')
pixel293 = tf.feature_column.numeric_column('pixel293')
pixel294 = tf.feature_column.numeric_column('pixel294')
pixel295 = tf.feature_column.numeric_column('pixel295')
pixel296 = tf.feature_column.numeric_column('pixel296')
pixel297 = tf.feature_column.numeric_column('pixel297')
pixel298 = tf.feature_column.numeric_column('pixel298')
pixel299 = tf.feature_column.numeric_column('pixel299')
pixel300 = tf.feature_column.numeric_column('pixel300')
pixel301 = tf.feature_column.numeric_column('pixel301')
pixel302 = tf.feature_column.numeric_column('pixel302')
pixel303 = tf.feature_column.numeric_column('pixel303')
pixel304 = tf.feature_column.numeric_column('pixel304')
pixel305 = tf.feature_column.numeric_column('pixel305')
pixel306 = tf.feature_column.numeric_column('pixel306')
pixel307 = tf.feature_column.numeric_column('pixel307')
pixel308 = tf.feature_column.numeric_column('pixel308')
pixel309 = tf.feature_column.numeric_column('pixel309')
pixel310 = tf.feature_column.numeric_column('pixel310')
pixel311 = tf.feature_column.numeric_column('pixel311')
pixel312 = tf.feature_column.numeric_column('pixel312')
pixel313 = tf.feature_column.numeric_column('pixel313')
pixel314 = tf.feature_column.numeric_column('pixel314')
pixel315 = tf.feature_column.numeric_column('pixel315')
pixel316 = tf.feature_column.numeric_column('pixel316')
pixel317 = tf.feature_column.numeric_column('pixel317')
pixel318 = tf.feature_column.numeric_column('pixel318')
pixel319 = tf.feature_column.numeric_column('pixel319')
pixel320 = tf.feature_column.numeric_column('pixel320')
pixel321 = tf.feature_column.numeric_column('pixel321')
pixel322 = tf.feature_column.numeric_column('pixel322')
pixel323 = tf.feature_column.numeric_column('pixel323')
pixel324 = tf.feature_column.numeric_column('pixel324')
pixel325 = tf.feature_column.numeric_column('pixel325')
pixel326 = tf.feature_column.numeric_column('pixel326')
pixel327 = tf.feature_column.numeric_column('pixel327')
pixel328 = tf.feature_column.numeric_column('pixel328')
pixel329 = tf.feature_column.numeric_column('pixel329')
pixel330 = tf.feature_column.numeric_column('pixel330')
pixel331 = tf.feature_column.numeric_column('pixel331')
pixel332 = tf.feature_column.numeric_column('pixel332')
pixel333 = tf.feature_column.numeric_column('pixel333')
pixel334 = tf.feature_column.numeric_column('pixel334')
pixel335 = tf.feature_column.numeric_column('pixel335')
pixel336 = tf.feature_column.numeric_column('pixel336')
pixel337 = tf.feature_column.numeric_column('pixel337')
pixel338 = tf.feature_column.numeric_column('pixel338')
pixel339 = tf.feature_column.numeric_column('pixel339')
pixel340 = tf.feature_column.numeric_column('pixel340')
pixel341 = tf.feature_column.numeric_column('pixel341')
pixel342 = tf.feature_column.numeric_column('pixel342')
pixel343 = tf.feature_column.numeric_column('pixel343')
pixel344 = tf.feature_column.numeric_column('pixel344')
pixel345 = tf.feature_column.numeric_column('pixel345')
pixel346 = tf.feature_column.numeric_column('pixel346')
pixel347 = tf.feature_column.numeric_column('pixel347')
pixel348 = tf.feature_column.numeric_column('pixel348')
pixel349 = tf.feature_column.numeric_column('pixel349')
pixel350 = tf.feature_column.numeric_column('pixel350')
pixel351 = tf.feature_column.numeric_column('pixel351')
pixel352 = tf.feature_column.numeric_column('pixel352')
pixel353 = tf.feature_column.numeric_column('pixel353')
pixel354 = tf.feature_column.numeric_column('pixel354')
pixel355 = tf.feature_column.numeric_column('pixel355')
pixel356 = tf.feature_column.numeric_column('pixel356')
pixel357 = tf.feature_column.numeric_column('pixel357')
pixel358 = tf.feature_column.numeric_column('pixel358')
pixel359 = tf.feature_column.numeric_column('pixel359')
pixel360 = tf.feature_column.numeric_column('pixel360')
pixel361 = tf.feature_column.numeric_column('pixel361')
pixel362 = tf.feature_column.numeric_column('pixel362')
pixel363 = tf.feature_column.numeric_column('pixel363')
pixel364 = tf.feature_column.numeric_column('pixel364')
pixel365 = tf.feature_column.numeric_column('pixel365')
pixel366 = tf.feature_column.numeric_column('pixel366')
pixel367 = tf.feature_column.numeric_column('pixel367')
pixel368 = tf.feature_column.numeric_column('pixel368')
pixel369 = tf.feature_column.numeric_column('pixel369')
pixel370 = tf.feature_column.numeric_column('pixel370')
pixel371 = tf.feature_column.numeric_column('pixel371')
pixel372 = tf.feature_column.numeric_column('pixel372')
pixel373 = tf.feature_column.numeric_column('pixel373')
pixel374 = tf.feature_column.numeric_column('pixel374')
pixel375 = tf.feature_column.numeric_column('pixel375')
pixel376 = tf.feature_column.numeric_column('pixel376')
pixel377 = tf.feature_column.numeric_column('pixel377')
pixel378 = tf.feature_column.numeric_column('pixel378')
pixel379 = tf.feature_column.numeric_column('pixel379')
pixel380 = tf.feature_column.numeric_column('pixel380')
pixel381 = tf.feature_column.numeric_column('pixel381')
pixel382 = tf.feature_column.numeric_column('pixel382')
pixel383 = tf.feature_column.numeric_column('pixel383')
pixel384 = tf.feature_column.numeric_column('pixel384')
pixel385 = tf.feature_column.numeric_column('pixel385')
pixel386 = tf.feature_column.numeric_column('pixel386')
pixel387 = tf.feature_column.numeric_column('pixel387')
pixel388 = tf.feature_column.numeric_column('pixel388')
pixel389 = tf.feature_column.numeric_column('pixel389')
pixel390 = tf.feature_column.numeric_column('pixel390')
pixel391 = tf.feature_column.numeric_column('pixel391')
pixel392 = tf.feature_column.numeric_column('pixel392')
pixel393 = tf.feature_column.numeric_column('pixel393')
pixel394 = tf.feature_column.numeric_column('pixel394')
pixel395 = tf.feature_column.numeric_column('pixel395')
pixel396 = tf.feature_column.numeric_column('pixel396')
pixel397 = tf.feature_column.numeric_column('pixel397')
pixel398 = tf.feature_column.numeric_column('pixel398')
pixel399 = tf.feature_column.numeric_column('pixel399')
pixel400 = tf.feature_column.numeric_column('pixel400')
pixel401 = tf.feature_column.numeric_column('pixel401')
pixel402 = tf.feature_column.numeric_column('pixel402')
pixel403 = tf.feature_column.numeric_column('pixel403')
pixel404 = tf.feature_column.numeric_column('pixel404')
pixel405 = tf.feature_column.numeric_column('pixel405')
pixel406 = tf.feature_column.numeric_column('pixel406')
pixel407 = tf.feature_column.numeric_column('pixel407')
pixel408 = tf.feature_column.numeric_column('pixel408')
pixel409 = tf.feature_column.numeric_column('pixel409')
pixel410 = tf.feature_column.numeric_column('pixel410')
pixel411 = tf.feature_column.numeric_column('pixel411')
pixel412 = tf.feature_column.numeric_column('pixel412')
pixel413 = tf.feature_column.numeric_column('pixel413')
pixel414 = tf.feature_column.numeric_column('pixel414')
pixel415 = tf.feature_column.numeric_column('pixel415')
pixel416 = tf.feature_column.numeric_column('pixel416')
pixel417 = tf.feature_column.numeric_column('pixel417')
pixel418 = tf.feature_column.numeric_column('pixel418')
pixel419 = tf.feature_column.numeric_column('pixel419')
pixel420 = tf.feature_column.numeric_column('pixel420')
pixel421 = tf.feature_column.numeric_column('pixel421')
pixel422 = tf.feature_column.numeric_column('pixel422')
pixel423 = tf.feature_column.numeric_column('pixel423')
pixel424 = tf.feature_column.numeric_column('pixel424')
pixel425 = tf.feature_column.numeric_column('pixel425')
pixel426 = tf.feature_column.numeric_column('pixel426')
pixel427 = tf.feature_column.numeric_column('pixel427')
pixel428 = tf.feature_column.numeric_column('pixel428')
pixel429 = tf.feature_column.numeric_column('pixel429')
pixel430 = tf.feature_column.numeric_column('pixel430')
pixel431 = tf.feature_column.numeric_column('pixel431')
pixel432 = tf.feature_column.numeric_column('pixel432')
pixel433 = tf.feature_column.numeric_column('pixel433')
pixel434 = tf.feature_column.numeric_column('pixel434')
pixel435 = tf.feature_column.numeric_column('pixel435')
pixel436 = tf.feature_column.numeric_column('pixel436')
pixel437 = tf.feature_column.numeric_column('pixel437')
pixel438 = tf.feature_column.numeric_column('pixel438')
pixel439 = tf.feature_column.numeric_column('pixel439')
pixel440 = tf.feature_column.numeric_column('pixel440')
pixel441 = tf.feature_column.numeric_column('pixel441')
pixel442 = tf.feature_column.numeric_column('pixel442')
pixel443 = tf.feature_column.numeric_column('pixel443')
pixel444 = tf.feature_column.numeric_column('pixel444')
pixel445 = tf.feature_column.numeric_column('pixel445')
pixel446 = tf.feature_column.numeric_column('pixel446')
pixel447 = tf.feature_column.numeric_column('pixel447')
pixel448 = tf.feature_column.numeric_column('pixel448')
pixel449 = tf.feature_column.numeric_column('pixel449')
pixel450 = tf.feature_column.numeric_column('pixel450')
pixel451 = tf.feature_column.numeric_column('pixel451')
pixel452 = tf.feature_column.numeric_column('pixel452')
pixel453 = tf.feature_column.numeric_column('pixel453')
pixel454 = tf.feature_column.numeric_column('pixel454')
pixel455 = tf.feature_column.numeric_column('pixel455')
pixel456 = tf.feature_column.numeric_column('pixel456')
pixel457 = tf.feature_column.numeric_column('pixel457')
pixel458 = tf.feature_column.numeric_column('pixel458')
pixel459 = tf.feature_column.numeric_column('pixel459')
pixel460 = tf.feature_column.numeric_column('pixel460')
pixel461 = tf.feature_column.numeric_column('pixel461')
pixel462 = tf.feature_column.numeric_column('pixel462')
pixel463 = tf.feature_column.numeric_column('pixel463')
pixel464 = tf.feature_column.numeric_column('pixel464')
pixel465 = tf.feature_column.numeric_column('pixel465')
pixel466 = tf.feature_column.numeric_column('pixel466')
pixel467 = tf.feature_column.numeric_column('pixel467')
pixel468 = tf.feature_column.numeric_column('pixel468')
pixel469 = tf.feature_column.numeric_column('pixel469')
pixel470 = tf.feature_column.numeric_column('pixel470')
pixel471 = tf.feature_column.numeric_column('pixel471')
pixel472 = tf.feature_column.numeric_column('pixel472')
pixel473 = tf.feature_column.numeric_column('pixel473')
pixel474 = tf.feature_column.numeric_column('pixel474')
pixel475 = tf.feature_column.numeric_column('pixel475')
pixel476 = tf.feature_column.numeric_column('pixel476')
pixel477 = tf.feature_column.numeric_column('pixel477')
pixel478 = tf.feature_column.numeric_column('pixel478')
pixel479 = tf.feature_column.numeric_column('pixel479')
pixel480 = tf.feature_column.numeric_column('pixel480')
pixel481 = tf.feature_column.numeric_column('pixel481')
pixel482 = tf.feature_column.numeric_column('pixel482')
pixel483 = tf.feature_column.numeric_column('pixel483')
pixel484 = tf.feature_column.numeric_column('pixel484')
pixel485 = tf.feature_column.numeric_column('pixel485')
pixel486 = tf.feature_column.numeric_column('pixel486')
pixel487 = tf.feature_column.numeric_column('pixel487')
pixel488 = tf.feature_column.numeric_column('pixel488')
pixel489 = tf.feature_column.numeric_column('pixel489')
pixel490 = tf.feature_column.numeric_column('pixel490')
pixel491 = tf.feature_column.numeric_column('pixel491')
pixel492 = tf.feature_column.numeric_column('pixel492')
pixel493 = tf.feature_column.numeric_column('pixel493')
pixel494 = tf.feature_column.numeric_column('pixel494')
pixel495 = tf.feature_column.numeric_column('pixel495')
pixel496 = tf.feature_column.numeric_column('pixel496')
pixel497 = tf.feature_column.numeric_column('pixel497')
pixel498 = tf.feature_column.numeric_column('pixel498')
pixel499 = tf.feature_column.numeric_column('pixel499')
pixel500 = tf.feature_column.numeric_column('pixel500')
pixel501 = tf.feature_column.numeric_column('pixel501')
pixel502 = tf.feature_column.numeric_column('pixel502')
pixel503 = tf.feature_column.numeric_column('pixel503')
pixel504 = tf.feature_column.numeric_column('pixel504')
pixel505 = tf.feature_column.numeric_column('pixel505')
pixel506 = tf.feature_column.numeric_column('pixel506')
pixel507 = tf.feature_column.numeric_column('pixel507')
pixel508 = tf.feature_column.numeric_column('pixel508')
pixel509 = tf.feature_column.numeric_column('pixel509')
pixel510 = tf.feature_column.numeric_column('pixel510')
pixel511 = tf.feature_column.numeric_column('pixel511')
pixel512 = tf.feature_column.numeric_column('pixel512')
pixel513 = tf.feature_column.numeric_column('pixel513')
pixel514 = tf.feature_column.numeric_column('pixel514')
pixel515 = tf.feature_column.numeric_column('pixel515')
pixel516 = tf.feature_column.numeric_column('pixel516')
pixel517 = tf.feature_column.numeric_column('pixel517')
pixel518 = tf.feature_column.numeric_column('pixel518')
pixel519 = tf.feature_column.numeric_column('pixel519')
pixel520 = tf.feature_column.numeric_column('pixel520')
pixel521 = tf.feature_column.numeric_column('pixel521')
pixel522 = tf.feature_column.numeric_column('pixel522')
pixel523 = tf.feature_column.numeric_column('pixel523')
pixel524 = tf.feature_column.numeric_column('pixel524')
pixel525 = tf.feature_column.numeric_column('pixel525')
pixel526 = tf.feature_column.numeric_column('pixel526')
pixel527 = tf.feature_column.numeric_column('pixel527')
pixel528 = tf.feature_column.numeric_column('pixel528')
pixel529 = tf.feature_column.numeric_column('pixel529')
pixel530 = tf.feature_column.numeric_column('pixel530')
pixel531 = tf.feature_column.numeric_column('pixel531')
pixel532 = tf.feature_column.numeric_column('pixel532')
pixel533 = tf.feature_column.numeric_column('pixel533')
pixel534 = tf.feature_column.numeric_column('pixel534')
pixel535 = tf.feature_column.numeric_column('pixel535')
pixel536 = tf.feature_column.numeric_column('pixel536')
pixel537 = tf.feature_column.numeric_column('pixel537')
pixel538 = tf.feature_column.numeric_column('pixel538')
pixel539 = tf.feature_column.numeric_column('pixel539')
pixel540 = tf.feature_column.numeric_column('pixel540')
pixel541 = tf.feature_column.numeric_column('pixel541')
pixel542 = tf.feature_column.numeric_column('pixel542')
pixel543 = tf.feature_column.numeric_column('pixel543')
pixel544 = tf.feature_column.numeric_column('pixel544')
pixel545 = tf.feature_column.numeric_column('pixel545')
pixel546 = tf.feature_column.numeric_column('pixel546')
pixel547 = tf.feature_column.numeric_column('pixel547')
pixel548 = tf.feature_column.numeric_column('pixel548')
pixel549 = tf.feature_column.numeric_column('pixel549')
pixel550 = tf.feature_column.numeric_column('pixel550')
pixel551 = tf.feature_column.numeric_column('pixel551')
pixel552 = tf.feature_column.numeric_column('pixel552')
pixel553 = tf.feature_column.numeric_column('pixel553')
pixel554 = tf.feature_column.numeric_column('pixel554')
pixel555 = tf.feature_column.numeric_column('pixel555')
pixel556 = tf.feature_column.numeric_column('pixel556')
pixel557 = tf.feature_column.numeric_column('pixel557')
pixel558 = tf.feature_column.numeric_column('pixel558')
pixel559 = tf.feature_column.numeric_column('pixel559')
pixel560 = tf.feature_column.numeric_column('pixel560')
pixel561 = tf.feature_column.numeric_column('pixel561')
pixel562 = tf.feature_column.numeric_column('pixel562')
pixel563 = tf.feature_column.numeric_column('pixel563')
pixel564 = tf.feature_column.numeric_column('pixel564')
pixel565 = tf.feature_column.numeric_column('pixel565')
pixel566 = tf.feature_column.numeric_column('pixel566')
pixel567 = tf.feature_column.numeric_column('pixel567')
pixel568 = tf.feature_column.numeric_column('pixel568')
pixel569 = tf.feature_column.numeric_column('pixel569')
pixel570 = tf.feature_column.numeric_column('pixel570')
pixel571 = tf.feature_column.numeric_column('pixel571')
pixel572 = tf.feature_column.numeric_column('pixel572')
pixel573 = tf.feature_column.numeric_column('pixel573')
pixel574 = tf.feature_column.numeric_column('pixel574')
pixel575 = tf.feature_column.numeric_column('pixel575')
pixel576 = tf.feature_column.numeric_column('pixel576')
pixel577 = tf.feature_column.numeric_column('pixel577')
pixel578 = tf.feature_column.numeric_column('pixel578')
pixel579 = tf.feature_column.numeric_column('pixel579')
pixel580 = tf.feature_column.numeric_column('pixel580')
pixel581 = tf.feature_column.numeric_column('pixel581')
pixel582 = tf.feature_column.numeric_column('pixel582')
pixel583 = tf.feature_column.numeric_column('pixel583')
pixel584 = tf.feature_column.numeric_column('pixel584')
pixel585 = tf.feature_column.numeric_column('pixel585')
pixel586 = tf.feature_column.numeric_column('pixel586')
pixel587 = tf.feature_column.numeric_column('pixel587')
pixel588 = tf.feature_column.numeric_column('pixel588')
pixel589 = tf.feature_column.numeric_column('pixel589')
pixel590 = tf.feature_column.numeric_column('pixel590')
pixel591 = tf.feature_column.numeric_column('pixel591')
pixel592 = tf.feature_column.numeric_column('pixel592')
pixel593 = tf.feature_column.numeric_column('pixel593')
pixel594 = tf.feature_column.numeric_column('pixel594')
pixel595 = tf.feature_column.numeric_column('pixel595')
pixel596 = tf.feature_column.numeric_column('pixel596')
pixel597 = tf.feature_column.numeric_column('pixel597')
pixel598 = tf.feature_column.numeric_column('pixel598')
pixel599 = tf.feature_column.numeric_column('pixel599')
pixel600 = tf.feature_column.numeric_column('pixel600')
pixel601 = tf.feature_column.numeric_column('pixel601')
pixel602 = tf.feature_column.numeric_column('pixel602')
pixel603 = tf.feature_column.numeric_column('pixel603')
pixel604 = tf.feature_column.numeric_column('pixel604')
pixel605 = tf.feature_column.numeric_column('pixel605')
pixel606 = tf.feature_column.numeric_column('pixel606')
pixel607 = tf.feature_column.numeric_column('pixel607')
pixel608 = tf.feature_column.numeric_column('pixel608')
pixel609 = tf.feature_column.numeric_column('pixel609')
pixel610 = tf.feature_column.numeric_column('pixel610')
pixel611 = tf.feature_column.numeric_column('pixel611')
pixel612 = tf.feature_column.numeric_column('pixel612')
pixel613 = tf.feature_column.numeric_column('pixel613')
pixel614 = tf.feature_column.numeric_column('pixel614')
pixel615 = tf.feature_column.numeric_column('pixel615')
pixel616 = tf.feature_column.numeric_column('pixel616')
pixel617 = tf.feature_column.numeric_column('pixel617')
pixel618 = tf.feature_column.numeric_column('pixel618')
pixel619 = tf.feature_column.numeric_column('pixel619')
pixel620 = tf.feature_column.numeric_column('pixel620')
pixel621 = tf.feature_column.numeric_column('pixel621')
pixel622 = tf.feature_column.numeric_column('pixel622')
pixel623 = tf.feature_column.numeric_column('pixel623')
pixel624 = tf.feature_column.numeric_column('pixel624')
pixel625 = tf.feature_column.numeric_column('pixel625')
pixel626 = tf.feature_column.numeric_column('pixel626')
pixel627 = tf.feature_column.numeric_column('pixel627')
pixel628 = tf.feature_column.numeric_column('pixel628')
pixel629 = tf.feature_column.numeric_column('pixel629')
pixel630 = tf.feature_column.numeric_column('pixel630')
pixel631 = tf.feature_column.numeric_column('pixel631')
pixel632 = tf.feature_column.numeric_column('pixel632')
pixel633 = tf.feature_column.numeric_column('pixel633')
pixel634 = tf.feature_column.numeric_column('pixel634')
pixel635 = tf.feature_column.numeric_column('pixel635')
pixel636 = tf.feature_column.numeric_column('pixel636')
pixel637 = tf.feature_column.numeric_column('pixel637')
pixel638 = tf.feature_column.numeric_column('pixel638')
pixel639 = tf.feature_column.numeric_column('pixel639')
pixel640 = tf.feature_column.numeric_column('pixel640')
pixel641 = tf.feature_column.numeric_column('pixel641')
pixel642 = tf.feature_column.numeric_column('pixel642')
pixel643 = tf.feature_column.numeric_column('pixel643')
pixel644 = tf.feature_column.numeric_column('pixel644')
pixel645 = tf.feature_column.numeric_column('pixel645')
pixel646 = tf.feature_column.numeric_column('pixel646')
pixel647 = tf.feature_column.numeric_column('pixel647')
pixel648 = tf.feature_column.numeric_column('pixel648')
pixel649 = tf.feature_column.numeric_column('pixel649')
pixel650 = tf.feature_column.numeric_column('pixel650')
pixel651 = tf.feature_column.numeric_column('pixel651')
pixel652 = tf.feature_column.numeric_column('pixel652')
pixel653 = tf.feature_column.numeric_column('pixel653')
pixel654 = tf.feature_column.numeric_column('pixel654')
pixel655 = tf.feature_column.numeric_column('pixel655')
pixel656 = tf.feature_column.numeric_column('pixel656')
pixel657 = tf.feature_column.numeric_column('pixel657')
pixel658 = tf.feature_column.numeric_column('pixel658')
pixel659 = tf.feature_column.numeric_column('pixel659')
pixel660 = tf.feature_column.numeric_column('pixel660')
pixel661 = tf.feature_column.numeric_column('pixel661')
pixel662 = tf.feature_column.numeric_column('pixel662')
pixel663 = tf.feature_column.numeric_column('pixel663')
pixel664 = tf.feature_column.numeric_column('pixel664')
pixel665 = tf.feature_column.numeric_column('pixel665')
pixel666 = tf.feature_column.numeric_column('pixel666')
pixel667 = tf.feature_column.numeric_column('pixel667')
pixel668 = tf.feature_column.numeric_column('pixel668')
pixel669 = tf.feature_column.numeric_column('pixel669')
pixel670 = tf.feature_column.numeric_column('pixel670')
pixel671 = tf.feature_column.numeric_column('pixel671')
pixel672 = tf.feature_column.numeric_column('pixel672')
pixel673 = tf.feature_column.numeric_column('pixel673')
pixel674 = tf.feature_column.numeric_column('pixel674')
pixel675 = tf.feature_column.numeric_column('pixel675')
pixel676 = tf.feature_column.numeric_column('pixel676')
pixel677 = tf.feature_column.numeric_column('pixel677')
pixel678 = tf.feature_column.numeric_column('pixel678')
pixel679 = tf.feature_column.numeric_column('pixel679')
pixel680 = tf.feature_column.numeric_column('pixel680')
pixel681 = tf.feature_column.numeric_column('pixel681')
pixel682 = tf.feature_column.numeric_column('pixel682')
pixel683 = tf.feature_column.numeric_column('pixel683')
pixel684 = tf.feature_column.numeric_column('pixel684')
pixel685 = tf.feature_column.numeric_column('pixel685')
pixel686 = tf.feature_column.numeric_column('pixel686')
pixel687 = tf.feature_column.numeric_column('pixel687')
pixel688 = tf.feature_column.numeric_column('pixel688')
pixel689 = tf.feature_column.numeric_column('pixel689')
pixel690 = tf.feature_column.numeric_column('pixel690')
pixel691 = tf.feature_column.numeric_column('pixel691')
pixel692 = tf.feature_column.numeric_column('pixel692')
pixel693 = tf.feature_column.numeric_column('pixel693')
pixel694 = tf.feature_column.numeric_column('pixel694')
pixel695 = tf.feature_column.numeric_column('pixel695')
pixel696 = tf.feature_column.numeric_column('pixel696')
pixel697 = tf.feature_column.numeric_column('pixel697')
pixel698 = tf.feature_column.numeric_column('pixel698')
pixel699 = tf.feature_column.numeric_column('pixel699')
pixel700 = tf.feature_column.numeric_column('pixel700')
pixel701 = tf.feature_column.numeric_column('pixel701')
pixel702 = tf.feature_column.numeric_column('pixel702')
pixel703 = tf.feature_column.numeric_column('pixel703')
pixel704 = tf.feature_column.numeric_column('pixel704')
pixel705 = tf.feature_column.numeric_column('pixel705')
pixel706 = tf.feature_column.numeric_column('pixel706')
pixel707 = tf.feature_column.numeric_column('pixel707')
pixel708 = tf.feature_column.numeric_column('pixel708')
pixel709 = tf.feature_column.numeric_column('pixel709')
pixel710 = tf.feature_column.numeric_column('pixel710')
pixel711 = tf.feature_column.numeric_column('pixel711')
pixel712 = tf.feature_column.numeric_column('pixel712')
pixel713 = tf.feature_column.numeric_column('pixel713')
pixel714 = tf.feature_column.numeric_column('pixel714')
pixel715 = tf.feature_column.numeric_column('pixel715')
pixel716 = tf.feature_column.numeric_column('pixel716')
pixel717 = tf.feature_column.numeric_column('pixel717')
pixel718 = tf.feature_column.numeric_column('pixel718')
pixel719 = tf.feature_column.numeric_column('pixel719')
pixel720 = tf.feature_column.numeric_column('pixel720')
pixel721 = tf.feature_column.numeric_column('pixel721')
pixel722 = tf.feature_column.numeric_column('pixel722')
pixel723 = tf.feature_column.numeric_column('pixel723')
pixel724 = tf.feature_column.numeric_column('pixel724')
pixel725 = tf.feature_column.numeric_column('pixel725')
pixel726 = tf.feature_column.numeric_column('pixel726')
pixel727 = tf.feature_column.numeric_column('pixel727')
pixel728 = tf.feature_column.numeric_column('pixel728')
pixel729 = tf.feature_column.numeric_column('pixel729')
pixel730 = tf.feature_column.numeric_column('pixel730')
pixel731 = tf.feature_column.numeric_column('pixel731')
pixel732 = tf.feature_column.numeric_column('pixel732')
pixel733 = tf.feature_column.numeric_column('pixel733')
pixel734 = tf.feature_column.numeric_column('pixel734')
pixel735 = tf.feature_column.numeric_column('pixel735')
pixel736 = tf.feature_column.numeric_column('pixel736')
pixel737 = tf.feature_column.numeric_column('pixel737')
pixel738 = tf.feature_column.numeric_column('pixel738')
pixel739 = tf.feature_column.numeric_column('pixel739')
pixel740 = tf.feature_column.numeric_column('pixel740')
pixel741 = tf.feature_column.numeric_column('pixel741')
pixel742 = tf.feature_column.numeric_column('pixel742')
pixel743 = tf.feature_column.numeric_column('pixel743')
pixel744 = tf.feature_column.numeric_column('pixel744')
pixel745 = tf.feature_column.numeric_column('pixel745')
pixel746 = tf.feature_column.numeric_column('pixel746')
pixel747 = tf.feature_column.numeric_column('pixel747')
pixel748 = tf.feature_column.numeric_column('pixel748')
pixel749 = tf.feature_column.numeric_column('pixel749')
pixel750 = tf.feature_column.numeric_column('pixel750')
pixel751 = tf.feature_column.numeric_column('pixel751')
pixel752 = tf.feature_column.numeric_column('pixel752')
pixel753 = tf.feature_column.numeric_column('pixel753')
pixel754 = tf.feature_column.numeric_column('pixel754')
pixel755 = tf.feature_column.numeric_column('pixel755')
pixel756 = tf.feature_column.numeric_column('pixel756')
pixel757 = tf.feature_column.numeric_column('pixel757')
pixel758 = tf.feature_column.numeric_column('pixel758')
pixel759 = tf.feature_column.numeric_column('pixel759')
pixel760 = tf.feature_column.numeric_column('pixel760')
pixel761 = tf.feature_column.numeric_column('pixel761')
pixel762 = tf.feature_column.numeric_column('pixel762')
pixel763 = tf.feature_column.numeric_column('pixel763')
pixel764 = tf.feature_column.numeric_column('pixel764')
pixel765 = tf.feature_column.numeric_column('pixel765')
pixel766 = tf.feature_column.numeric_column('pixel766')
pixel767 = tf.feature_column.numeric_column('pixel767')
pixel768 = tf.feature_column.numeric_column('pixel768')
pixel769 = tf.feature_column.numeric_column('pixel769')
pixel770 = tf.feature_column.numeric_column('pixel770')
pixel771 = tf.feature_column.numeric_column('pixel771')
pixel772 = tf.feature_column.numeric_column('pixel772')
pixel773 = tf.feature_column.numeric_column('pixel773')
pixel774 = tf.feature_column.numeric_column('pixel774')
pixel775 = tf.feature_column.numeric_column('pixel775')
pixel776 = tf.feature_column.numeric_column('pixel776')
pixel777 = tf.feature_column.numeric_column('pixel777')
pixel778 = tf.feature_column.numeric_column('pixel778')
pixel779 = tf.feature_column.numeric_column('pixel779')
pixel780 = tf.feature_column.numeric_column('pixel780')
pixel781 = tf.feature_column.numeric_column('pixel781')
pixel782 = tf.feature_column.numeric_column('pixel782')
pixel783 = tf.feature_column.numeric_column('pixel783')

In [30]:
print(str(['pixel'+str(i) for i in range(784)]).replace("'", ""))

[pixel0, pixel1, pixel2, pixel3, pixel4, pixel5, pixel6, pixel7, pixel8, pixel9, pixel10, pixel11, pixel12, pixel13, pixel14, pixel15, pixel16, pixel17, pixel18, pixel19, pixel20, pixel21, pixel22, pixel23, pixel24, pixel25, pixel26, pixel27, pixel28, pixel29, pixel30, pixel31, pixel32, pixel33, pixel34, pixel35, pixel36, pixel37, pixel38, pixel39, pixel40, pixel41, pixel42, pixel43, pixel44, pixel45, pixel46, pixel47, pixel48, pixel49, pixel50, pixel51, pixel52, pixel53, pixel54, pixel55, pixel56, pixel57, pixel58, pixel59, pixel60, pixel61, pixel62, pixel63, pixel64, pixel65, pixel66, pixel67, pixel68, pixel69, pixel70, pixel71, pixel72, pixel73, pixel74, pixel75, pixel76, pixel77, pixel78, pixel79, pixel80, pixel81, pixel82, pixel83, pixel84, pixel85, pixel86, pixel87, pixel88, pixel89, pixel90, pixel91, pixel92, pixel93, pixel94, pixel95, pixel96, pixel97, pixel98, pixel99, pixel100, pixel101, pixel102, pixel103, pixel104, pixel105, pixel106, pixel107, pixel108, pixel109, pixel110,

In [31]:
feat_cols = [pixel0, pixel1, pixel2, pixel3, pixel4, pixel5, pixel6, pixel7, pixel8, pixel9, pixel10, pixel11, pixel12, pixel13, pixel14, pixel15, pixel16, pixel17, pixel18, pixel19, pixel20, pixel21, pixel22, pixel23, pixel24, pixel25, pixel26, pixel27, pixel28, pixel29, pixel30, pixel31, pixel32, pixel33, pixel34, pixel35, pixel36, pixel37, pixel38, pixel39, pixel40, pixel41, pixel42, pixel43, pixel44, pixel45, pixel46, pixel47, pixel48, pixel49, pixel50, pixel51, pixel52, pixel53, pixel54, pixel55, pixel56, pixel57, pixel58, pixel59, pixel60, pixel61, pixel62, pixel63, pixel64, pixel65, pixel66, pixel67, pixel68, pixel69, pixel70, pixel71, pixel72, pixel73, pixel74, pixel75, pixel76, pixel77, pixel78, pixel79, pixel80, pixel81, pixel82, pixel83, pixel84, pixel85, pixel86, pixel87, pixel88, pixel89, pixel90, pixel91, pixel92, pixel93, pixel94, pixel95, pixel96, pixel97, pixel98, pixel99, pixel100, pixel101, pixel102, pixel103, pixel104, pixel105, pixel106, pixel107, pixel108, pixel109, pixel110, pixel111, pixel112, pixel113, pixel114, pixel115, pixel116, pixel117, pixel118, pixel119, pixel120, pixel121, pixel122, pixel123, pixel124, pixel125, pixel126, pixel127, pixel128, pixel129, pixel130, pixel131, pixel132, pixel133, pixel134, pixel135, pixel136, pixel137, pixel138, pixel139, pixel140, pixel141, pixel142, pixel143, pixel144, pixel145, pixel146, pixel147, pixel148, pixel149, pixel150, pixel151, pixel152, pixel153, pixel154, pixel155, pixel156, pixel157, pixel158, pixel159, pixel160, pixel161, pixel162, pixel163, pixel164, pixel165, pixel166, pixel167, pixel168, pixel169, pixel170, pixel171, pixel172, pixel173, pixel174, pixel175, pixel176, pixel177, pixel178, pixel179, pixel180, pixel181, pixel182, pixel183, pixel184, pixel185, pixel186, pixel187, pixel188, pixel189, pixel190, pixel191, pixel192, pixel193, pixel194, pixel195, pixel196, pixel197, pixel198, pixel199, pixel200, pixel201, pixel202, pixel203, pixel204, pixel205, pixel206, pixel207, pixel208, pixel209, pixel210, pixel211, pixel212, pixel213, pixel214, pixel215, pixel216, pixel217, pixel218, pixel219, pixel220, pixel221, pixel222, pixel223, pixel224, pixel225, pixel226, pixel227, pixel228, pixel229, pixel230, pixel231, pixel232, pixel233, pixel234, pixel235, pixel236, pixel237, pixel238, pixel239, pixel240, pixel241, pixel242, pixel243, pixel244, pixel245, pixel246, pixel247, pixel248, pixel249, pixel250, pixel251, pixel252, pixel253, pixel254, pixel255, pixel256, pixel257, pixel258, pixel259, pixel260, pixel261, pixel262, pixel263, pixel264, pixel265, pixel266, pixel267, pixel268, pixel269, pixel270, pixel271, pixel272, pixel273, pixel274, pixel275, pixel276, pixel277, pixel278, pixel279, pixel280, pixel281, pixel282, pixel283, pixel284, pixel285, pixel286, pixel287, pixel288, pixel289, pixel290, pixel291, pixel292, pixel293, pixel294, pixel295, pixel296, pixel297, pixel298, pixel299, pixel300, pixel301, pixel302, pixel303, pixel304, pixel305, pixel306, pixel307, pixel308, pixel309, pixel310, pixel311, pixel312, pixel313, pixel314, pixel315, pixel316, pixel317, pixel318, pixel319, pixel320, pixel321, pixel322, pixel323, pixel324, pixel325, pixel326, pixel327, pixel328, pixel329, pixel330, pixel331, pixel332, pixel333, pixel334, pixel335, pixel336, pixel337, pixel338, pixel339, pixel340, pixel341, pixel342, pixel343, pixel344, pixel345, pixel346, pixel347, pixel348, pixel349, pixel350, pixel351, pixel352, pixel353, pixel354, pixel355, pixel356, pixel357, pixel358, pixel359, pixel360, pixel361, pixel362, pixel363, pixel364, pixel365, pixel366, pixel367, pixel368, pixel369, pixel370, pixel371, pixel372, pixel373, pixel374, pixel375, pixel376, pixel377, pixel378, pixel379, pixel380, pixel381, pixel382, pixel383, pixel384, pixel385, pixel386, pixel387, pixel388, pixel389, pixel390, pixel391, pixel392, pixel393, pixel394, pixel395, pixel396, pixel397, pixel398, pixel399, pixel400, pixel401, pixel402, pixel403, pixel404, pixel405, pixel406, pixel407, pixel408, pixel409, pixel410, pixel411, pixel412, pixel413, pixel414, pixel415, pixel416, pixel417, pixel418, pixel419, pixel420, pixel421, pixel422, pixel423, pixel424, pixel425, pixel426, pixel427, pixel428, pixel429, pixel430, pixel431, pixel432, pixel433, pixel434, pixel435, pixel436, pixel437, pixel438, pixel439, pixel440, pixel441, pixel442, pixel443, pixel444, pixel445, pixel446, pixel447, pixel448, pixel449, pixel450, pixel451, pixel452, pixel453, pixel454, pixel455, pixel456, pixel457, pixel458, pixel459, pixel460, pixel461, pixel462, pixel463, pixel464, pixel465, pixel466, pixel467, pixel468, pixel469, pixel470, pixel471, pixel472, pixel473, pixel474, pixel475, pixel476, pixel477, pixel478, pixel479, pixel480, pixel481, pixel482, pixel483, pixel484, pixel485, pixel486, pixel487, pixel488, pixel489, pixel490, pixel491, pixel492, pixel493, pixel494, pixel495, pixel496, pixel497, pixel498, pixel499, pixel500, pixel501, pixel502, pixel503, pixel504, pixel505, pixel506, pixel507, pixel508, pixel509, pixel510, pixel511, pixel512, pixel513, pixel514, pixel515, pixel516, pixel517, pixel518, pixel519, pixel520, pixel521, pixel522, pixel523, pixel524, pixel525, pixel526, pixel527, pixel528, pixel529, pixel530, pixel531, pixel532, pixel533, pixel534, pixel535, pixel536, pixel537, pixel538, pixel539, pixel540, pixel541, pixel542, pixel543, pixel544, pixel545, pixel546, pixel547, pixel548, pixel549, pixel550, pixel551, pixel552, pixel553, pixel554, pixel555, pixel556, pixel557, pixel558, pixel559, pixel560, pixel561, pixel562, pixel563, pixel564, pixel565, pixel566, pixel567, pixel568, pixel569, pixel570, pixel571, pixel572, pixel573, pixel574, pixel575, pixel576, pixel577, pixel578, pixel579, pixel580, pixel581, pixel582, pixel583, pixel584, pixel585, pixel586, pixel587, pixel588, pixel589, pixel590, pixel591, pixel592, pixel593, pixel594, pixel595, pixel596, pixel597, pixel598, pixel599, pixel600, pixel601, pixel602, pixel603, pixel604, pixel605, pixel606, pixel607, pixel608, pixel609, pixel610, pixel611, pixel612, pixel613, pixel614, pixel615, pixel616, pixel617, pixel618, pixel619, pixel620, pixel621, pixel622, pixel623, pixel624, pixel625, pixel626, pixel627, pixel628, pixel629, pixel630, pixel631, pixel632, pixel633, pixel634, pixel635, pixel636, pixel637, pixel638, pixel639, pixel640, pixel641, pixel642, pixel643, pixel644, pixel645, pixel646, pixel647, pixel648, pixel649, pixel650, pixel651, pixel652, pixel653, pixel654, pixel655, pixel656, pixel657, pixel658, pixel659, pixel660, pixel661, pixel662, pixel663, pixel664, pixel665, pixel666, pixel667, pixel668, pixel669, pixel670, pixel671, pixel672, pixel673, pixel674, pixel675, pixel676, pixel677, pixel678, pixel679, pixel680, pixel681, pixel682, pixel683, pixel684, pixel685, pixel686, pixel687, pixel688, pixel689, pixel690, pixel691, pixel692, pixel693, pixel694, pixel695, pixel696, pixel697, pixel698, pixel699, pixel700, pixel701, pixel702, pixel703, pixel704, pixel705, pixel706, pixel707, pixel708, pixel709, pixel710, pixel711, pixel712, pixel713, pixel714, pixel715, pixel716, pixel717, pixel718, pixel719, pixel720, pixel721, pixel722, pixel723, pixel724, pixel725, pixel726, pixel727, pixel728, pixel729, pixel730, pixel731, pixel732, pixel733, pixel734, pixel735, pixel736, pixel737, pixel738, pixel739, pixel740, pixel741, pixel742, pixel743, pixel744, pixel745, pixel746, pixel747, pixel748, pixel749, pixel750, pixel751, pixel752, pixel753, pixel754, pixel755, pixel756, pixel757, pixel758, pixel759, pixel760, pixel761, pixel762, pixel763, pixel764, pixel765, pixel766, pixel767, pixel768, pixel769, pixel770, pixel771, pixel772, pixel773, pixel774, pixel775, pixel776, pixel777, pixel778, pixel779, pixel780, pixel781, pixel782, pixel783]

In [32]:
train_input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=10, num_epochs=1000, shuffle=True)

In [33]:
eval_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test, y=y_test, batch_size=10, num_epochs=1, shuffle=False)

In [34]:
pred_train_input_func = tf.estimator.inputs.pandas_input_fn(x=train_images.drop(['label'], axis=1), y=train_images['label'], batch_size=10, num_epochs=1000, shuffle=True)

In [35]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=test_images, batch_size=10, num_epochs=1, shuffle=False)

# DNN Clasiifier

In [36]:
model = tf.estimator.DNNClassifier(hidden_units=[784,1568,784], feature_columns=feat_cols, n_classes=10)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_device_fn': None, '_log_step_count_steps': 100, '_save_checkpoints_secs': 600, '_tf_random_seed': None, '_session_config': None, '_train_distribute': None, '_evaluation_master': '', '_num_ps_replicas': 0, '_global_id_in_cluster': 0, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0, '_model_dir': 'C:\\Users\\Ritvik\\AppData\\Local\\Temp\\tmpjyhmivt2', '_save_summary_steps': 100, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000024837430390>, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_master': '', '_num_worker_replicas': 1, '_service': None, '_task_type': 'worker'}


In [37]:
model.train(input_fn=train_input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Ritvik\AppData\Local\Temp\tmpjyhmivt2\model.ckpt.
INFO:tensorflow:loss = 869.746, step = 1
INFO:tensorflow:global_step/sec: 10.4723
INFO:tensorflow:loss = 41.828, step = 101 (9.565 sec)
INFO:tensorflow:global_step/sec: 13.1674
INFO:tensorflow:loss = 6.25035, step = 201 (7.598 sec)
INFO:tensorflow:global_step/sec: 12.883
INFO:tensorflow:loss = 10.0286, step = 301 (7.742 sec)
INFO:tensorflow:global_step/sec: 13.0487
INFO:tensorflow:loss = 6.12543, step = 401 (7.681 sec)
INFO:tensorflow:global_step/sec: 12.4059
INFO:tensorflow:loss = 12.4344, step = 501 (8.059 sec)
INFO:tensorflow:global_step/sec: 12.9441
INFO:tensorflow:loss = 14.9693, step = 601 (7.716 sec)
INFO:tensorflow:global_step/sec: 12.7945
IN

In [38]:
results = model.evaluate(input_fn=eval_input_func)
print('\nResults: {}'.format(results))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-09-22-21:26:57
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Ritvik\AppData\Local\Temp\tmpjyhmivt2\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-09-22-21:28:15
INFO:tensorflow:Saving dict for global step 1000: accuracy = 0.83619, average_loss = 0.64782, global_step = 1000, loss = 6.4782
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: C:\Users\Ritvik\AppData\Local\Temp\tmpjyhmivt2\model.ckpt-1000

Results: {'loss': 6.478199, 'average_loss': 0.64781988, 'global_step': 1000, 'accuracy': 0.83619046}


In [39]:
model = tf.estimator.DNNClassifier(hidden_units=[784,1568,784], feature_columns=feat_cols, n_classes=10)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_device_fn': None, '_log_step_count_steps': 100, '_save_checkpoints_secs': 600, '_tf_random_seed': None, '_session_config': None, '_train_distribute': None, '_evaluation_master': '', '_num_ps_replicas': 0, '_global_id_in_cluster': 0, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0, '_model_dir': 'C:\\Users\\Ritvik\\AppData\\Local\\Temp\\tmpfz1_pd8w', '_save_summary_steps': 100, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000024861EE4048>, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_master': '', '_num_worker_replicas': 1, '_service': None, '_task_type': 'worker'}


In [40]:
model.train(input_fn=pred_train_input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Ritvik\AppData\Local\Temp\tmpfz1_pd8w\model.ckpt.
INFO:tensorflow:loss = 687.592, step = 1
INFO:tensorflow:global_step/sec: 10.6628
INFO:tensorflow:loss = 15.3541, step = 101 (9.376 sec)
INFO:tensorflow:global_step/sec: 12.8353
INFO:tensorflow:loss = 16.9549, step = 201 (7.793 sec)
INFO:tensorflow:global_step/sec: 12.495
INFO:tensorflow:loss = 22.5808, step = 301 (8.000 sec)
INFO:tensorflow:global_step/sec: 12.6645
INFO:tensorflow:loss = 6.3308, step = 401 (7.913 sec)
INFO:tensorflow:global_step/sec: 12.8249
INFO:tensorflow:loss = 14.277, step = 501 (7.783 sec)
INFO:tensorflow:global_step/sec: 12.673
INFO:tensorflow:loss = 11.0934, step = 601 (7.909 sec)
INFO:tensorflow:global_step/sec: 12.8817
INFO

In [41]:
predictions = []
pred = model.predict(input_fn=pred_input_func)
for p in pred:
    predictions.append(str(p['classes'])[3])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Ritvik\AppData\Local\Temp\tmpfz1_pd8w\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [42]:
submissions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(predictions, columns=['label'])], axis=1)
submissions.to_csv('DNNEstimator.csv', index=False)

# Linear Classifier

In [43]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols, n_classes=10)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_device_fn': None, '_log_step_count_steps': 100, '_save_checkpoints_secs': 600, '_tf_random_seed': None, '_session_config': None, '_train_distribute': None, '_evaluation_master': '', '_num_ps_replicas': 0, '_global_id_in_cluster': 0, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0, '_model_dir': 'C:\\Users\\Ritvik\\AppData\\Local\\Temp\\tmp_zp7kfr8', '_save_summary_steps': 100, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000248130FDB00>, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_master': '', '_num_worker_replicas': 1, '_service': None, '_task_type': 'worker'}


In [44]:
model.train(input_fn=train_input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Ritvik\AppData\Local\Temp\tmp_zp7kfr8\model.ckpt.
INFO:tensorflow:loss = 23.0259, step = 1
INFO:tensorflow:global_step/sec: 7.57972
INFO:tensorflow:loss = 628.938, step = 101 (13.193 sec)
INFO:tensorflow:global_step/sec: 20.3664
INFO:tensorflow:loss = 0.0631351, step = 201 (4.930 sec)
INFO:tensorflow:global_step/sec: 14.2411
INFO:tensorflow:loss = 246.353, step = 301 (7.034 sec)
INFO:tensorflow:global_step/sec: 14.2501
INFO:tensorflow:loss = 0.0, step = 401 (7.080 sec)
INFO:tensorflow:global_step/sec: 13.9313
INFO:tensorflow:loss = 562.389, step = 501 (7.100 sec)
INFO:tensorflow:global_step/sec: 14.3428
INFO:tensorflow:loss = 1920.28, step = 601 (6.972 sec)
INFO:tensorflow:global_step/sec: 13.8367
I

In [45]:
results = model.evaluate(input_fn=eval_input_func)
print('\nResults: {}'.format(results))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-09-22-21:42:30
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Ritvik\AppData\Local\Temp\tmp_zp7kfr8\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-09-22-21:44:02
INFO:tensorflow:Saving dict for global step 1000: accuracy = 0.860667, average_loss = 87.9999, global_step = 1000, loss = 879.999
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: C:\Users\Ritvik\AppData\Local\Temp\tmp_zp7kfr8\model.ckpt-1000

Results: {'loss': 879.99908, 'average_loss': 87.999908, 'global_step': 1000, 'accuracy': 0.86066669}


In [46]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols, n_classes=10)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_device_fn': None, '_log_step_count_steps': 100, '_save_checkpoints_secs': 600, '_tf_random_seed': None, '_session_config': None, '_train_distribute': None, '_evaluation_master': '', '_num_ps_replicas': 0, '_global_id_in_cluster': 0, '_keep_checkpoint_every_n_hours': 10000, '_task_id': 0, '_model_dir': 'C:\\Users\\Ritvik\\AppData\\Local\\Temp\\tmp2is5di76', '_save_summary_steps': 100, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000248F1E1F5C0>, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_master': '', '_num_worker_replicas': 1, '_service': None, '_task_type': 'worker'}


In [47]:
model.train(input_fn=pred_train_input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Ritvik\AppData\Local\Temp\tmp2is5di76\model.ckpt.
INFO:tensorflow:loss = 23.0259, step = 1
INFO:tensorflow:global_step/sec: 7.42489
INFO:tensorflow:loss = 992.485, step = 101 (13.468 sec)
INFO:tensorflow:global_step/sec: 21.0387
INFO:tensorflow:loss = 2028.15, step = 201 (4.769 sec)
INFO:tensorflow:global_step/sec: 14.0003
INFO:tensorflow:loss = 2397.09, step = 301 (7.143 sec)
INFO:tensorflow:global_step/sec: 14.0692
INFO:tensorflow:loss = 85.9404, step = 401 (7.155 sec)
INFO:tensorflow:global_step/sec: 13.7977
INFO:tensorflow:loss = 1711.73, step = 501 (7.201 sec)
INFO:tensorflow:global_step/sec: 12.8162
INFO:tensorflow:loss = 0.0, step = 601 (7.818 sec)
INFO:tensorflow:global_step/sec: 13.9255
INF

In [48]:
predictions = []
pred = model.predict(input_fn=pred_input_func)
for p in pred:
    predictions.append(str(p['classes'])[3])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Ritvik\AppData\Local\Temp\tmp2is5di76\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [49]:
submissions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(predictions, columns=['label'])], axis=1)
submissions.to_csv('LinearEstimator.csv', index=False)

# Keras Softmax

In [50]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [71]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(train_images['label'])
encoded_Y = encoder.transform(train_images['label'])
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

X_trainK, X_testK, y_trainK, y_testK = train_test_split(train_images.drop(['label'], axis=1), dummy_y)

# 784->397->10

In [52]:
def neuralnet():
    model = Sequential()
    model.add(Dense(397, init='uniform', activation='relu', input_dim=784))
    model.add(Dense(10, init='uniform', activation='sigmoid'))
    model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='rmsprop')
    return model

In [53]:
network = KerasClassifier(build_fn=neuralnet, batch_size=25, nb_epoch=100)

In [54]:
accuracies = cross_val_score(estimator=network, X=X_trainK, y=y_trainK, cv=10)
print("{} +- ({})".format(accuracies.mean(), accuracies.std()))

D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(397, kernel_initializer="uniform", input_dim=784, activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, kernel_initializer="uniform", activation="sigmoid")`
  after removing the cwd from sys.path.


Epoch 1/1
3150/3150 [==============================] - 0s 95us/step
Epoch 1/1
3150/3150 [==============================] - 0s 95us/step
Epoch 1/1
3150/3150 [==============================] - 0s 96us/step
Epoch 1/1
3150/3150 [==============================] - 0s 97us/step
Epoch 1/1
3150/3150 [==============================] - 0s 101us/step
Epoch 1/1
3150/3150 [==============================] - 0s 102us/step
Epoch 1/1
3150/3150 [==============================] - 0s 107us/step
Epoch 1/1
3150/3150 [==============================] - 0s 103us/step
Epoch 1/1
3150/3150 [==============================] - 0s 109us/step
Epoch 1/1
3150/3150 [==============================] - 0s 113us/step
0.14946031578121677 +- (0.11804964121693437)


In [55]:
network = neuralnet()
network.fit(train_images.drop(['label'], axis=1), dummy_y, batch_size=25, nb_epoch=100)

D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(397, kernel_initializer="uniform", input_dim=784, activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, kernel_initializer="uniform", activation="sigmoid")`
  after removing the cwd from sys.path.
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
42000/42000 [==============================] - 14s 327us/step - loss: 2.4362 - acc: 0.3875
Epoch 2/100
42000/42000 [==============================] - 16s 379us/step - loss: 3.1560 - acc: 0.4825
Epoch 3/100
42000/42000 [==============================] - 13s 307us/step - loss: 3.6197 - acc: 0.5037
Epoch 4/100
42000/42000 [==============================] - 13s 306us/step - loss: 3.4648 - acc: 0.5116
Epoch 5/100
42000/42000 [==============================] - 13s 307us/step - loss: 3.4953 - acc: 0.5184
Epoch 6/100
42000/42000 [==============================] - 13s 310us/step - loss: 3.4818 - acc: 0.5164
Epoch 7/100
42000/42000 [==============================] - 13s 307us/step - loss: 3.4750 - acc: 0.5225
Epoch 8/100
42000/42000 [==============================] - 13s 307us/step - loss: 3.4853 - acc: 0.5219
Epoch 9/100
42000/42000 [==============================] - 13s 310us/step - loss: 3.4695 - acc: 0.5254
Epoch 10/100
42000/42000 [==============================] - 13s 313us/ste

42000/42000 [==============================] - 14s 330us/step - loss: 3.3992 - acc: 0.5464
Epoch 80/100
42000/42000 [==============================] - 13s 307us/step - loss: 3.3472 - acc: 0.5480
Epoch 81/100
42000/42000 [==============================] - 13s 314us/step - loss: 3.4050 - acc: 0.5445
Epoch 82/100
42000/42000 [==============================] - 13s 317us/step - loss: 3.3496 - acc: 0.5470
Epoch 83/100
42000/42000 [==============================] - 13s 316us/step - loss: 3.3075 - acc: 0.5509
Epoch 84/100
42000/42000 [==============================] - 14s 335us/step - loss: 3.3650 - acc: 0.5508
Epoch 85/100
42000/42000 [==============================] - 13s 317us/step - loss: 3.4253 - acc: 0.5447
Epoch 86/100
42000/42000 [==============================] - 14s 325us/step - loss: 3.2389 - acc: 0.5540
Epoch 87/100
42000/42000 [==============================] - 14s 323us/step - loss: 3.1790 - acc: 0.5535
Epoch 88/100
42000/42000 [==============================] - 13s 317us/step - 

In [56]:
y_pred = network.predict(test_images)

In [57]:
print(y_pred[:5])
prediction = []
for y in y_pred:
    prediction.append(y.tolist().index((max(y))))

[[ 0.  0.  1.  0.  0.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  1.  0.  0.  1.  0.]]


In [58]:
submissions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(prediction, columns=['label'])], axis=1)
submissions.to_csv('Keras.csv', index=False)

# 784->1568->784->10

In [68]:
def neuralnet():
    model = Sequential()
    model.add(Dense(1568, init='uniform', activation='relu', input_dim=784))
    model.add(Dense(784, init='uniform', activation='relu'))
    model.add(Dense(10, init='uniform', activation='sigmoid'))
    model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='rmsprop')
    return model

In [69]:
network = KerasClassifier(build_fn=neuralnet, batch_size=25, nb_epoch=100)

In [72]:
accuracies = cross_val_score(estimator=network, X=X_trainK, y=y_trainK, cv=10)
print("{} +- ({})".format(accuracies.mean(), accuracies.std()))

D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1568, kernel_initializer="uniform", input_dim=784, activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(784, kernel_initializer="uniform", activation="relu")`
  after removing the cwd from sys.path.
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, kernel_initializer="uniform", activation="sigmoid")`
  """


Epoch 1/1
3150/3150 [==============================] - 1s 276us/step
Epoch 1/1
3150/3150 [==============================] - 1s 336us/step
Epoch 1/1
3150/3150 [==============================] - 1s 287us/step
Epoch 1/1
3150/3150 [==============================] - 1s 313us/step
Epoch 1/1
3150/3150 [==============================] - 1s 295us/step
Epoch 1/1
3150/3150 [==============================] - 1s 292us/step
Epoch 1/1
3150/3150 [==============================] - 1s 304us/step
Epoch 1/1
3150/3150 [==============================] - 1s 309us/step
Epoch 1/1
3150/3150 [==============================] - 1s 314us/step
Epoch 1/1
3150/3150 [==============================] - 1s 322us/step
0.10085714111134174 +- (0.005700247235201615)


In [73]:
network = neuralnet()
network.fit(train_images.drop(['label'], axis=1), dummy_y, batch_size=25, nb_epoch=100)

D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1568, kernel_initializer="uniform", input_dim=784, activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(784, kernel_initializer="uniform", activation="relu")`
  after removing the cwd from sys.path.
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, kernel_initializer="uniform", activation="sigmoid")`
  """
D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
42000/42000 [==============================] - 53s 1ms/step - loss: 9.1437 - acc: 0.1042
Epoch 2/100
42000/42000 [==============================] - 50s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 3/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 4/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 5/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 6/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 7/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 8/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 9/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 10/100
42000/42000 [==============================] - 52s 1ms/step - loss: 9.0216 - a

42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 82/100
42000/42000 [==============================] - 52s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 83/100
42000/42000 [==============================] - 52s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 84/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 85/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 86/100
42000/42000 [==============================] - 51s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 87/100
42000/42000 [==============================] - 55s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 88/100
42000/42000 [==============================] - 56s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 89/100
42000/42000 [==============================] - 54s 1ms/step - loss: 9.0216 - acc: 0.1036
Epoch 90/100
42000/42000 [==============================] - 57s 1ms/step - loss: 9.0216 - acc: 

In [74]:
y_pred = network.predict(test_images)

In [75]:
print(y_pred[:5])
prediction = []
for y in y_pred:
    prediction.append(y.tolist().index((max(y))))

[[ 0.  0.  0.  1.  1.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.  0.  1.]]


In [77]:
submissions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(prediction, columns=['label'])], axis=1)
submissions.to_csv('Keras2.csv', index=False)

# Keras CNN

In [59]:
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D, Flatten, Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [60]:
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(train_images['label'])
encoded_Y = encoder.transform(train_images['label'])
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

X_trainK, X_testK, y_trainK, y_testK = train_test_split(train_images.drop(['label'], axis=1), dummy_y)

X_trainK = X_trainK.values.reshape(-1,28,28,1)
X_testK = X_testK.values.reshape(-1,28,28,1)

In [61]:
def cnn():
    model = Sequential()
    model.add(Convolution2D(32, (2, 2), input_shape = (28, 28, 1), activation='relu', padding='same', strides=2))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
    return model

In [62]:
network = KerasClassifier(build_fn=cnn, batch_size=25, nb_epoch=100)

In [63]:
accuracies = cross_val_score(estimator=network, X=X_trainK, y=y_trainK, cv=10)
print("{} +- ({})".format(accuracies.mean(), accuracies.std()))

Epoch 1/1
3150/3150 [==============================] - 1s 191us/step
Epoch 1/1
3150/3150 [==============================] - 1s 210us/step
Epoch 1/1
3150/3150 [==============================] - 1s 214us/step
Epoch 1/1
3150/3150 [==============================] - 1s 222us/step
Epoch 1/1
3150/3150 [==============================] - 1s 215us/step
Epoch 1/1
3150/3150 [==============================] - 1s 229us/step
Epoch 1/1
3150/3150 [==============================] - 1s 231us/step
Epoch 1/1
3150/3150 [==============================] - 1s 241us/step
Epoch 1/1
3150/3150 [==============================] - 1s 258us/step
Epoch 1/1
3150/3150 [==============================] - 1s 252us/step
0.30504761924819335 +- (0.1814194187102955)


In [64]:
network = cnn()
network.fit(train_images.drop(['label'], axis=1).values.reshape(-1,28,28,1), dummy_y, batch_size=25, nb_epoch=100)

D:\Users\Ritvik\Anaconda3\envs\tfdeeplearning\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
42000/42000 [==============================] - 19s 458us/step - loss: 4.4393 - acc: 0.6803
Epoch 2/100
42000/42000 [==============================] - 18s 439us/step - loss: 0.1581 - acc: 0.9510
Epoch 3/100
42000/42000 [==============================] - 18s 439us/step - loss: 0.1109 - acc: 0.9652
Epoch 4/100
42000/42000 [==============================] - 18s 438us/step - loss: 0.0933 - acc: 0.9697
Epoch 5/100
42000/42000 [==============================] - 18s 435us/step - loss: 0.0780 - acc: 0.9741
Epoch 6/100
42000/42000 [==============================] - 19s 443us/step - loss: 0.0635 - acc: 0.9785
Epoch 7/100
42000/42000 [==============================] - 18s 436us/step - loss: 0.0560 - acc: 0.9810
Epoch 8/100
42000/42000 [==============================] - 19s 442us/step - loss: 0.0498 - acc: 0.9835
Epoch 9/100
42000/42000 [==============================] - 19s 442us/step - loss: 0.0396 - acc: 0.9867
Epoch 10/100
42000/42000 [==============================] - 18s 436us/ste

42000/42000 [==============================] - 19s 448us/step - loss: 0.0263 - acc: 0.9972
Epoch 80/100
42000/42000 [==============================] - 18s 433us/step - loss: 0.0599 - acc: 0.9948
Epoch 81/100
42000/42000 [==============================] - 18s 436us/step - loss: 0.0351 - acc: 0.9969
Epoch 82/100
42000/42000 [==============================] - 18s 434us/step - loss: 0.0497 - acc: 0.9954
Epoch 83/100
42000/42000 [==============================] - 18s 434us/step - loss: 0.0446 - acc: 0.9959
Epoch 84/100
42000/42000 [==============================] - 18s 439us/step - loss: 0.0439 - acc: 0.9960
Epoch 85/100
42000/42000 [==============================] - 18s 436us/step - loss: 0.0269 - acc: 0.9974
Epoch 86/100
42000/42000 [==============================] - 18s 435us/step - loss: 0.0405 - acc: 0.9966
Epoch 87/100
42000/42000 [==============================] - 18s 436us/step - loss: 0.0535 - acc: 0.9954
Epoch 88/100
42000/42000 [==============================] - 19s 450us/step - 

In [65]:
y_pred = network.predict(test_images.values.reshape(-1,28,28,1))

In [66]:
print(y_pred[:5])
prediction = []
for y in y_pred:
    prediction.append(y.tolist().index((max(y))))

[[  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   2.10441524e-15
    0.00000000e+00   1.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]]


In [67]:
submissions = pd.concat([pd.DataFrame(np.arange(1, 28001), columns=['ImageId']), pd.DataFrame(prediction, columns=['label'])], axis=1)
submissions.to_csv('KerasCNN.csv', index=False)